spring:
  application.name: bemestar-java
  profiles.active: dev

management.endpoints.web.exposure.include: health,info

---
spring:
  config.activate.on-profile: dev
  h2.console.enabled: true
  h2.console.path: /h2-console
  datasource:
    url: jdbc:h2:mem:bemestar;MODE=Oracle;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
    properties.hibernate.format_sql: true
  flyway.locations: classpath:db/migration
  cache:
    type: caffeine
caffeine:
  spec: maximumSize=1000,expireAfterWrite=5m
---
spring:
  config.activate.on-profile: prod
  datasource:
    url: ${ORACLE_URL}
    username: ${ORACLE_USER}
    password: ${ORACLE_PASS}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate.ddl-auto: validate

    springdoc:
      paths-to-match: /v1/**         # documenta s√≥ seus endpoints da API
      default-consumes-media-type: application/json
      default-produces-media-type: application/json

    logging:
      level:
        org.springdoc: INFO          # use DEBUG se ainda der 500 para ver o stacktrace




