spring:
  application.name: bemestar-java
  profiles.active: dev

management.endpoints.web.exposure.include: health,info

---
spring:
  config.activate.on-profile: dev
  datasource:
    url: jdbc:h2:mem:bemestar;MODE=Oracle
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
    properties.hibernate.format_sql: true
  flyway.locations: classpath:db/migration

---
spring:
  config.activate.on-profile: prod
  datasource:
    url: ${ORACLE_URL}
    username: ${ORACLE_USER}
    password: ${ORACLE_PASS}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate.ddl-auto: validate
