spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:testdb;MODE=Oracle;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  flyway:
    locations: classpath:db/migration
  rabbitmq:
    listener:
      simple:
        missing-queues-fatal: false

# Mensageria sempre desabilitada em testes
messaging:
  enabled: false
