spring:
  application:
    name: bemestar-java
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  paths-to-match: /v1/**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
logging:
  level:
    org.springdoc: INFO

# ===================== DEV =====================
---
spring:
  config:
    activate:
      on-profile: dev

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:bemestar;MODE=Oracle;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    locations: classpath:db/migration

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=5m

  ai:
    ollama:
      base-url: http://localhost:11434/
      chat:
        options:
          model: qwen3:4b
          temperature: 0.2
          top-p: 0.9
          max-tokens: 512

  # Evita falhar se fila não existir em dev (especialmente com mensageria off)
  rabbitmq:
    listener:
      simple:
        missing-queues-fatal: false

# flag de mensageria (DEV: desligada por padrão)
messaging:
  enabled: false

app:
  mq:
    ritmo:
      exchange: bemestar.ritmo.exchange
      queue: bemestar.ritmo.queue
      routingKey: bemestar.ritmo.key


# ===================== PROD =====================
---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${ORACLE_URL}
    username: ${ORACLE_USER}
    password: ${ORACLE_PASS}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: validate

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=5m

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}
    listener:
      simple:
        missing-queues-fatal: false

springdoc:
  paths-to-match: /v1/**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# Em produção você decide por variável de ambiente
messaging:
  enabled: ${MESSAGING_ENABLED:false}

app:
  mq:
    ritmo:
      exchange: ${RITMO_EXCHANGE:bemestar.ritmo.exchange}
      queue: ${RITMO_QUEUE:bemestar.ritmo.queue}
      routingKey: ${RITMO_ROUTING_KEY:bemestar.ritmo.key}
